### ISSUE TITLE
Kickass plugin not working

### ISSUE THREAD

**Issue by gumpster2010** [ebukari/qbittorrent-plugins#1]
Hey ebukari --

I noticed that my qBittorrent search isn't pulling up any results on Kickass even for searches that yield results online. Do you know if the plugin needs updating? I would love to search using my qBittorrent client.

Thanks!

**Comment by ebukari** [comment]
I pushed a commit that solved the issue. Just remove the current plugin and then add it.

**Comment by gumpster2010** [comment]
Hm I uninstalled and reinstalled it still doesn't work... no results show up. Are you sure the issue was resolved? 

Thank you for working on this!
